### ISSUE TITLE
`[Cypress-SignalR-Mock] - [cy.hubPublish] - HubConnectionMock not found

### ISSUE THREAD

**Issue by Jisco** [JasonLandbridge/Cypress-SignalR-Mock#7]
Hi,
i get this error method `[Cypress-SignalR-Mock] - [cy.hubPublish] - HubConnectionMock not found for usersHub`.

The mock is instantiated but only contains one hub named “default”. Any ideas why my mock dont is registering?
There are no errors and everything seems to work in the initialization.

```ts
this.connection =
  useCypressSignalRMock("usersHub")??
  new HubConnectionBuilder()
    .withUrl(`${server}/usersHub`, {
      XXX
    })
    .configureLogging(isDev ? LogLevel.Debug : LogLevel.Error)
    .withAutomaticReconnect()
    .build();

await this.connection.start();
```

```ts
cy.hubPublish("usersHub", "XXX", {
  ...
});
```

Versions:
@microsoft/signalr: 8.0.7
cypress: 13.13.2

**Comment by JasonLandbridge** [comment]
@Jisco Hi! This package hasn't been updated yet for .NET 8.0, you're welcome to make a quick PR for it and then I will merge it

**Comment by Jisco** [comment]
Hello,
sure, but I tried locally with version 7 of @microsoft/signalr and got the same error.

But, ok I'll create a PR tomorrow and try this out properly

**Comment by Jisco** [comment]
https://github.com/JasonLandbridge/Cypress-SignalR-Mock/pull/8

But i dont think this resolves my problem because i dont need to do any code changes...

**Comment by JasonLandbridge** [comment]
Apologies, I misread your post and I might have wrongly assumed it was the same error I got which was most likely due to the outdated .NET version. 

Are you sure there is a space before the `??` ? Your sample shows `useCypressSignalRMock("usersHub")??`, not sure if this matters but can't hurt to check

When you do `console.log(window["cypress-signalr-mock"])` is there an object that shows the plugin got loaded correctly?

Any chance your example is in an open-source project or can you provide more info?

**Comment by Jisco** [comment]
> Are you sure there is a space before the ?? ? Your sample shows useCypressSignalRMock("usersHub")??, not sure if this matters but can't hurt to check

No this seems not to be the problem.

> Any chance your example is in an open-source project or can you provide more info?
I will try to setup a small example in the next days

**Comment by Jisco** [comment]
Thanks for the tip: console.log(window["cypress-signalr-mock"]). It seems like Cypress is simply trying to resolve the mock before it has been initialized.

Looks like I just need to get the whole thing in the right order, I have no idea why Cypress treats asynchronous processes so strangely 😆 

If I can't solve the problem, I'll get back to you, otherwise it can probably be closed here.

Thanks for the help

**Comment by JasonLandbridge** [comment]
Happy to help! And thank you for the PR, will shortly take a look at it!

**Comment by Jisco** [comment]
FYI: It works if i just do it in the correct way. My bad. So this can be closed. 🆗
